-------- ORIGINAL DATA --------
SELECT *
FROM CONSUMER_DATA;

SELECT *
FROM NETFLIX_TITLES;

SELECT *
FROM VIEWING_BEHAVIOUR_DATA;

-------- GENERAL ANALYSIS --------
---- Gender breakdown.
SELECT GENDER, COUNT(GENDER)
FROM CONSUMER_DATA
GROUP BY GENDER
ORDER BY GENDER;

---- Subscription breakdown.
WITH
	CTE AS (
		SELECT *, COUNT(*) OVER () AS TOTAL_COUNT
		FROM CONSUMER_DATA
	)
SELECT 
	SUBSCRIPTION_PLAN, 
	COUNT(*),
	ROUND(COUNT(*) * 100.0 / TOTAL_COUNT, 2) AS PERCENTAGE
FROM CTE
GROUP BY SUBSCRIPTION_PLAN, TOTAL_COUNT;

---- Age breakdown.
SELECT
	AGE,
	COUNT(AGE)
FROM CONSUMER_DATA
GROUP BY AGE
ORDER BY AGE;

---- Age range breakdown.
WITH
	CTE AS (
		SELECT
			CASE
				WHEN AGE BETWEEN 10 AND 25  THEN 'Gen Z'
				WHEN AGE BETWEEN 26 AND 41  THEN 'Millennials'
				WHEN AGE BETWEEN 42 AND 57  THEN 'Gen X'
				WHEN AGE BETWEEN 58 AND 76  THEN 'Baby Boomers'
				ELSE 'Silent Generation'
			END AS GENERATION,
			COUNT(*) AS COUNT
		FROM CONSUMER_DATA
		GROUP BY GENERATION
		ORDER BY COUNT DESC
	)
SELECT *, ROUND(COUNT * 100.0 / 100000, 2) AS PERCENT
FROM CTE;

---- Show breakdown.
SELECT SHOW_TYPE, COUNT(*)
FROM NETFLIX_TITLES
GROUP BY SHOW_TYPE;

---- Genre breakdown.
SELECT 
	BTRIM(UNNEST(STRING_TO_ARRAY(LISTED_IN, ','))) AS GENRE,
	COUNT(*)
FROM NETFLIX_TITLES
GROUP BY GENRE
ORDER BY COUNT(*) DESC
LIMIT 10;

-- User country breakdown.
SELECT COUNTRY, COUNT(*)
FROM CONSUMER_DATA
GROUP BY COUNTRY
ORDER BY COUNT DESC;

---- General activity.
SELECT
	EXTRACT(YEAR FROM WATCH_DATE) AS YEAR,
	EXTRACT(MONTH FROM WATCH_DATE) AS MONTH,
	COUNT(*)
FROM VIEWING_BEHAVIOUR_DATA
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

-- Show country breakdown.
WITH CTE AS (
	SELECT 
		BTRIM(UNNEST(STRING_TO_ARRAY(COUNTRY, ','))) AS COUNTRY,
		COUNT(*)
	FROM NETFLIX_TITLES NT
	GROUP BY COUNTRY
)
SELECT 
	COUNTRY,
	SUM(COUNT) AS FREQ
FROM CTE
GROUP BY COUNTRY
ORDER BY FREQ DESC;

---- Genre popularity actitvity.
SELECT
	BTRIM(UNNEST(STRING_TO_ARRAY(LISTED_IN, ','))) AS GENRE,
	EXTRACT(YEAR FROM WATCH_DATE) AS YEAR,
	COUNT(*)
FROM
	VIEWING_BEHAVIOUR_DATA VBA
	JOIN NETFLIX_TITLES NT ON VBA.CONTENT_ID = NT.SHOW_ID
GROUP BY GENRE, YEAR
ORDER BY GENRE, YEAR;

---- Subscriptions activity per country.
SELECT
	COUNTRY,
	EXTRACT(YEAR FROM SUBSCRIPTION_START_DATE) AS YEAR,
	COUNT(*)
FROM CONSUMER_DATA CD
GROUP BY COUNTRY, YEAR
ORDER BY COUNT DESC, COUNTRY, YEAR;

SELECT *, BTRIM(UNNEST(STRING_TO_ARRAY(LISTED_IN, ','))) AS GENRE
FROM NETFLIX_TITLES AS NT;

SELECT COUNT(*) FROM consumer_data;